myparser: y.tab.c lex.yy.c y.tab.h
	gcc y.tab.c lex.yy.c -g -ll -o myparser
lex.yy.c: lex.l
	lex lex.l
y.tab.c: yacc.y
	yacc -v -d -g yacc.y
clean:
	rm -f myparser y.tab.c lex.yy.c y.tab.h y.output y.dot a.out
execute1:
	./myparser TEST_FILES/test1